### ISSUE TITLE
Sequence number is not reported correctly in the report_status script.

### ISSUE THREAD

**Issue by cristic83** [severalnines/galera-docker-mariadb#5]
In the report_status script the sequence number is reported under the name wsrep_last_committed, while in the entrypoint the sequence number is checked under the key seqno. This creates the possibility of having two separate clusters if two nodes in a Kubernetes cluster are drained one after the other (galera-2, then galera-1) and uncordoned at the same time.
The suggested fix is to report the sequence number under the key seqno in the report_status script too.

[fix_the_reporting_of_seqno_.patch.txt](https://github.com/severalnines/galera-docker-mariadb/files/1652582/fix_the_reporting_of_seqno_.patch.txt)

**Comment by ashraf-s9s** [comment]
Hi @cristic83 

Patch applied to report_status.sh. I'm closing down this issue.
